name: 'Bug Report'
description: 'Use this template for reporting an issue.'
labels: 'Triage'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit a report.
        **Please don't forget to update the issue title.**
        Include all applicable information to help us reproduce

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        What is not working? What were you expecting? Are there any workarounds?
        Remember that a missing profile or a short log will make extremely difficult
        to investigate your case or provide any help, please be as specific as possible.
      placeholder: Include all applicable information with details to help us reproduce your problem
    validations:
      required: true

  - type: textarea
    id: current_behavior
    attributes:
      label: Current Behavior
      description: Tell us what happens instead of the expected behavior.
      placeholder: When trying to do X, I get Y
    validations:
      required: true


  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: Tell us what happens instead of the expected behavior.
      placeholder: What I get instead is Z
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: |
        Provide an unambiguous set of steps to reproduce this bug.
        Provide a link to a model that has the bug (a minimum complete and verifiable example (MCVE) is preferred) and/or code to reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      value: |
        1.
        2.
        3.
        4.
    validations:
      required: true

  - type: textarea
    id: possible_solution
    attributes:
      label: Possible Solution
      description: |
        Optional, but if you can, suggest a fix/reason for the bug
    validations:
      required: false

  - type: dropdown
    id: download
    attributes:
      label: Platform and Operating System affected
      options:
        - Homebrew
        - MacPorts
        - apt-get
        - Built from source
    validations:
      required: true

  - type: checkboxes
    id: operation_checkboxes
    attributes:
      label: What kinds of cats do you like?
      description: You may select more than one.
      options:
        - label: macOS x86_64
        - label: macOS arm64
        - label: Ubuntu 18.04
        - label: Ubuntu 20.04
        - label: Windows 10
        - label: Windows 11

  - type: textarea
    id: env
    attributes:
      label: Environment
      description: Some additional details about your environment for this issue (if relevant)
      value: |
        * Platform (Operating system, version, architecture): **Linux Ubuntu 18.04**
        * Version of OpenStudio (if using an intermediate build, include SHA): **3.5.0**
      placeholder: |
        lsb_release --all
        uname -i
        openstudio --version
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: How has this issue affected you? What are you trying to accomplish?
    validations:
      required: false
