name: 'Test if Env variables are persisted'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash

    - id: random-number-generator
      shell: bash
      run: echo "random-id=$RANDOM" >> $GITHUB_OUTPUT

    - name: Set up env variable
      shell: bash
      run: |
        echo "NEW_ENV=helloworld" >> $GITHUB_ENV


    - name: Prepand to PATH
      shell: bash
      run: |
        echo "PATH=NewEntryOnENV:$PATH" >> $GITHUB_ENV
        echo "NewEntryOnPath" >> $GITHUB_PATH
