name: Test Python

on:
  push:

jobs:
  test_python:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/setup-python@v5
      id: setup-python
      with:
        python-version: '3.12'

    - name: Echo echo echo the lights they go
      run: |
        echo "steps.setup-python.outputs.python-version = ${{ steps.setup-python.outputs.python-version }}"
        echo "steps.setup-python.outputs.python-path = ${{ steps.setup-python.outputs.python-path }}"

        PYTHON_VERSION=${{ steps.setup-python.outputs.python-version }}
        Python_ROOT_DIR=$(python -c "from pathlib import Path; print(Path('${{ steps.setup-python.outputs.python-path }}').parent.parent)")
        echo "Python_ROOT_DIR=$Python_ROOT_DIR"

        Python_ROOT_DIR="$(dirname "$(dirname "${{ steps.setup-python.outputs.python-path }}")")"
        echo "Python_ROOT_DIR=$Python_ROOT_DIR"

        echo $RUNNER_TOOL_CACHE/Python/$PYTHON_VERSION/x64
        ls $RUNNER_TOOL_CACHE/Python/$PYTHON_VERSION/x64
