name: Test needrestart

on:
  push:

jobs:

  build:
    # Note: as of 2021-01-29, this only works for push, not for pull request
    #if: "!(contains(github.event.head_commit.message, 'skip') && contains(github.event.head_commit.message, 'ci'))"
    runs-on: ubuntu-24.04

    steps:
    - name: install libssl-dev
      run: |
        sudo apt update -qq
        sudo apt install -y libssl-dev

    - name: ok?
      run: |
        echo "ok"
