name: Test Miktex

on:
  push:
    branches: [ master, develop ]


defaults:
  run:
    shell: bash

jobs:

  build:
    # Note: as of 2021-01-29, this only works for push, not for pull request
    #if: "!(contains(github.event.head_commit.message, 'skip') && contains(github.event.head_commit.message, 'ci'))"
    runs-on: ${{ matrix.os }}
    strategy:
      # fail-fast: Default is true, switch to false to allow one platform to fail and still run others
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]

    steps:

    - name: Curl to api2.miktex.org
      shell: bash
      run: |
        curl -v -I https://api2.miktex.org/hello
