name: Docker Test

on:
  push:
    branches: [ "main", "docker" ]
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      with:
        submodules: true
        lfs: true

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          repo/app
        tags: |
          type=ref,event=branch
          type=semver,pattern={{version}}

    - name: Build and export to Docker (local)
      uses: docker/build-push-action@v4
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      with:
        context: .
        load: true
        tags: repo/app:test

    - name: Test docker
      run: |
        docker run --rm repo/app:test
        docker run --rm repo/app:test ls

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        provenance: false
        cache-from: type=gha
        cache-to: type=gha,mode=max

