name: Loguru problem matcher

on:
  push:

env:
  # https://github.com/actions/runner/issues/2341 - problem matcher do not work on colored output
  LOGURU_FORMAT: "[<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level: <8}</level> | {file}:{line} | {name}:<cyan>{function}</cyan> - <level>{message}</level>]"
  #LOGURU_FORMAT: "[{time:YYYY-MM-DD HH:mm:ss.SSS} | {level: <8} | {file}:{line} | {name}:{function} - <level>{message}</level>]"

jobs:
  integration-test:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install loguru
      run: pip install loguru

    - name: Add problem matcher
      run: echo "::add-matcher::.github/workflows/integration_problem_matcher.json"

    - name: integration-test
      run: |
        python loguru_test.py
