name: Merge Queue Check

on:
  merge_group:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Require [Pass-Merge] in commit message
        env:
          COMMIT_MESSAGE: ${{ github.event.merge_group.head_commit.message }}
        run: |
          if [[ "$COMMIT_MESSAGE" == *"[Pass-Merge]"* ]]; then
            echo 'assuming all checks pass'
          else
            echo "Commit message does not contain [Pass-Merge]"
            exit 1
          fi
