name: Workflow with a Dispatch

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag name for which to run it (eg: v3.2.2). If not specified, defaults to the latest release'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Hello
      shell: bash
      run: |
        echo "TAG_NAME=${{ github.event.inputs.tag }}"
