name: Test gfortran

on:
  push:
    branches: [ gfortran ]

jobs:

  build:
    # Note: as of 2021-01-29, this only works for push, not for pull request
    #if: "!(contains(github.event.head_commit.message, 'skip') && contains(github.event.head_commit.message, 'ci'))"
    runs-on: ${{ matrix.os }}
    strategy:
      # fail-fast: Default is true, switch to false to allow one platform to fail and still run others
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04, windows-latest, macos-latest]


    steps:
    - name: test gfortran
      shell: bash
      run: |
        set -x
        which gcc || true
        gcc --version || true
        which gfortran || true
        gfortran --version || true

        gfortran-9 --version || true
        gfortran-10 --version || true
        gfortran-12 --version || true
        gfortran-13 --version || true
        gfortran-14 --version || true
