name: Test OpenStudio Python Bindings

on:
  workflow_dispatch:
    inputs:
      package_version:
        description: 'Which release version to check'
        required: true
        default: '3.1.1a14'
      use_pypi:
        description: 'Whether to use testpy (default, false) or pypi (true)'
        required: true
        default: 'false'

jobs:
  test_python_bindings:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.allow_failure }}
    strategy:
      # fail-fast: Default is true, switch to false to allow one platform to fail and still run others
      fail-fast: false
      matrix:
        name: [Ubuntu, macOS, Windows_py37, Windows_py38, Windows_py39]
        include:
        - name: Ubuntu
          os: ubuntu-24.04
          python-version: 3.8
          allow_failure: false
        - name: macOS
          os: macos-13
          python-version: 3.8
          allow_failure: false
        - name: Windows_py37
          os: windows-2019
          python-version: 3.7
          allow_failure: false
        - name: Windows_py38
          os: windows-2019
          python-version: 3.8
          allow_failure: false
        - name: Windows_py39
          os: windows-2019
          python-version: 3.9
          allow_failure: true  # Possible this fails, don't care yet

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install openstudio bindings from testpypi
      if: github.event.inputs.use_pypi != 'true'
      run: |
          pip install -i https://test.pypi.org/simple/ openstudio==${{ github.event.inputs.package_version  }}

    - name: Test the bindings
      shell: python
      run: |
          import openstudio
          m = openstudio.model.exampleModel()
          print(m)
