name: Test bed

on:
  push:

env:
  TRUE_BOOL: true

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Call my own action
      uses: ./.github/actions/test_env
      with:
        who-to-greet: 'Mona the Octocat'

    - name: Retrieve composite action output
      shell: bash
      run: echo random-number ${{ steps.foo.outputs.random-number }}

    - name: the env variable IS persisted
      shell: bash
      run: |
        echo $NEW_ENV
        env

    - name: Is the PATH persisted
      shell: bash
      run: |
        echo $PATH | tr : '\n'

    - name: Print content
      shell: bash
      run: |
        tree

    - name: Try a second checkout
      uses: actions/checkout@v5
      with:
        ref: test_clang-format

    - name: Print content
      shell: bash
      run: |
        tree
